package signing

import (
	"encoding/hex"
	"net/url"
	"os"
	"strings"
	"testing"
	"time"
)

// The golden vector file is the contract between the Go signer and every other implementation of
// it — starting with the C++ one in clients/cpp, which dariyakyu will vendor when it has to verify
// capability tokens.
//
// This exists because of the failure it prevents. If Go and C++ disagree about a trailing slash,
// a "+", or the order of two query parameters, nothing fails loudly: every request simply returns
// 403, identically to a wrong secret, at whatever hour the two implementations first meet. A
// byte-equality test against shared vectors turns that into a red build.
//
// Format is deliberately not JSON. Every variable-length field is hex, so there is nothing to
// escape and a C++ parser is twenty lines with no dependency — and a dependency-free C++ client is
// the point, since it gets vendored into repos that should not inherit OpenSSL.
const vectorFile = "testdata/signing_vectors.txt"

type vector struct {
	name      string
	method    string
	path      string
	query     url.Values
	body      []byte
	secret    []byte
	accessKey string
	region    string
	service   string
	at        time.Time
}

func vectors() []vector {
	base := time.Date(2026, 9, 23, 6, 45, 17, 0, time.UTC)
	secret := []byte("a-signing-secret")

	return []vector{
		{
			name: "simple_get", method: "GET", path: "/ping",
			secret: secret, accessKey: "DARIYAKEYABCDEFGHIJKLMNO",
			region: "hind-1", service: "ws", at: base,
		},
		{
			name: "post_with_body", method: "POST", path: "/2026-09-18/functions/resize/invocations",
			query: url.Values{"qualifier": {"live"}}, body: []byte(`{"hello":"world"}`),
			secret: secret, accessKey: "DARIYAKEYABCDEFGHIJKLMNO",
			region: "hind-1", service: "func", at: base,
		},
		{
			// Query ordering: the canonical form must not depend on how a client happened to
			// build the map.
			name: "unsorted_query", method: "GET", path: "/queues",
			query:  url.Values{"z": {"26"}, "a": {"1"}, "m": {"13"}},
			secret: secret, accessKey: "DARIYAKEYABCDEFGHIJKLMNO",
			region: "hind-1", service: "kyu", at: base,
		},
		{
			// Repeated values sort among themselves.
			name: "repeated_query", method: "GET", path: "/queues",
			query:  url.Values{"tag": {"z", "a", "m"}},
			secret: secret, accessKey: "DARIYAKEYABCDEFGHIJKLMNO",
			region: "hind-1", service: "kyu", at: base,
		},
		{
			// The encoding trap. A space, a plus and a tilde each have a different answer, and
			// url.QueryEscape would get two of the three wrong for this scheme.
			name: "encoding_edges", method: "GET", path: "/queues/my queue+one~two",
			query:  url.Values{"filter": {"a b+c~d"}},
			secret: secret, accessKey: "DARIYAKEYABCDEFGHIJKLMNO",
			region: "hind-1", service: "kyu", at: base,
		},
		{
			// A path that is only a slash, and an empty body.
			name: "root_path", method: "GET", path: "/",
			secret: secret, accessKey: "DARIYAKEYABCDEFGHIJKLMNO",
			region: "hind-1", service: "ws", at: base,
		},
		{
			// Non-ASCII, which must be percent-encoded byte by byte rather than by rune.
			name: "utf8_path", method: "GET", path: "/queues/दरिया",
			secret: secret, accessKey: "DARIYAKEYABCDEFGHIJKLMNO",
			region: "hind-1", service: "kyu", at: base,
		},
		{
			// A secret with non-printable bytes, so an implementation that treats it as a
			// C string fails here rather than in production.
			name: "binary_secret", method: "GET", path: "/ping",
			secret:    []byte{0x00, 0x01, 0xff, 0xfe, 'a', 0x00, 'b'},
			accessKey: "DARIYAKEYABCDEFGHIJKLMNO",
			region:    "hind-1", service: "ws", at: base,
		},
	}
}

func renderVectors() string {
	var b strings.Builder
	b.WriteString("# dariyanWS signing vectors — generated by `go test ./internal/signing -run TestSigningVectors`.\n")
	b.WriteString("# Every variable-length field is hex so there is nothing to escape.\n")
	b.WriteString("# A second implementation is correct when it reproduces `canonical` and `signature`.\n")

	for _, v := range vectors() {
		ts := v.at.UTC().Format(TimeFormat)
		scope := Scope{AccessKeyID: v.accessKey, Date: ts[:8], Region: v.region, Service: v.service}
		req := Request{Method: v.method, Path: v.path, Query: v.query, Body: v.body}

		canonical := CanonicalString(req, scope, ts)
		auth, _ := Sign(req, Credentials{AccessKeyID: v.accessKey, Secret: v.secret},
			v.region, v.service, v.at)
		sig, err := ParseAuthorization(auth)
		if err != nil {
			panic(err)
		}

		b.WriteString("\ncase " + v.name + "\n")
		b.WriteString("method " + v.method + "\n")
		b.WriteString("path " + hex.EncodeToString([]byte(v.path)) + "\n")
		b.WriteString("query " + hex.EncodeToString([]byte(v.query.Encode())) + "\n")
		b.WriteString("timestamp " + ts + "\n")
		b.WriteString("accesskey " + v.accessKey + "\n")
		b.WriteString("region " + v.region + "\n")
		b.WriteString("service " + v.service + "\n")
		b.WriteString("body " + hex.EncodeToString(v.body) + "\n")
		b.WriteString("secret " + hex.EncodeToString(v.secret) + "\n")
		b.WriteString("canonical " + hex.EncodeToString([]byte(canonical)) + "\n")
		b.WriteString("signature " + sig.Signature + "\n")
	}
	return b.String()
}

// TestSigningVectors regenerates the file and fails if it changed.
//
// A change here is a change to the wire format: every signature every client ever computed becomes
// different. That is allowed, but it must be deliberate, so it shows up as a failing test and a
// visible diff rather than as a silent regeneration during an unrelated commit. Run with
// -update after a change you meant.
func TestSigningVectors(t *testing.T) {
	want := renderVectors()

	if os.Getenv("UPDATE_VECTORS") == "1" {
		if err := os.WriteFile(vectorFile, []byte(want), 0o644); err != nil {
			t.Fatalf("write vectors: %v", err)
		}
		t.Logf("wrote %s", vectorFile)
		return
	}

	got, err := os.ReadFile(vectorFile)
	if err != nil {
		t.Fatalf("read vectors (UPDATE_VECTORS=1 go test ./internal/signing to create): %v", err)
	}
	if string(got) != want {
		t.Errorf("%s is stale — the signing scheme changed.\n"+
			"Every existing client's signatures are now different. If that was deliberate, "+
			"regenerate with UPDATE_VECTORS=1 and update clients/cpp alongside it.", vectorFile)
	}
}

// The vectors are only worth anything if they round-trip through Verify, or a bug could be frozen
// into the golden file and then faithfully reproduced by every other implementation.
func TestVectorsVerify(t *testing.T) {
	for _, v := range vectors() {
		t.Run(v.name, func(t *testing.T) {
			req := Request{Method: v.method, Path: v.path, Query: v.query, Body: v.body}
			auth, headers := Sign(req, Credentials{AccessKeyID: v.accessKey, Secret: v.secret},
				v.region, v.service, v.at)
			sig, err := ParseAuthorization(auth)
			if err != nil {
				t.Fatalf("parse: %v", err)
			}
			if err := Verify(VerifyInput{
				Request: req, Signature: sig,
				DateHeaderValue:     headers[DateHeader],
				ContentSHA256Header: headers[ContentSHA256Header],
				Secret:              v.secret, Region: v.region, Service: v.service,
				Now: v.at,
			}); err != nil {
				t.Errorf("vector does not verify: %v", err)
			}
		})
	}
}
