#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <string>
#include <string_view>

namespace dariya {

// SHA-256, self-contained.
//
// Bundled rather than linked against OpenSSL on purpose. This client gets vendored into the
// service repos — dariyakyu will need it to verify capability tokens — and none of them should
// inherit a crypto dependency, a brew path, or a CMake find_package dance for one hash function.
//
// The risk of hand-rolling a hash is that it is subtly wrong and nothing notices. That is
// answered two ways: the NIST test vectors in tests/, and the cross-language vectors generated by
// the Go implementation, which this must reproduce byte for byte.
class Sha256 {
public:
    static constexpr std::size_t kDigestBytes = 32;
    static constexpr std::size_t kBlockBytes = 64;

    using Digest = std::array<std::uint8_t, kDigestBytes>;

    Sha256();

    void update(const void* data, std::size_t len);
    void update(std::string_view s) { update(s.data(), s.size()); }

    // Finalises. The object must not be updated afterwards.
    Digest finish();

    static Digest hash(const void* data, std::size_t len);
    static Digest hash(std::string_view s) { return hash(s.data(), s.size()); }

private:
    void compress(const std::uint8_t block[kBlockBytes]);

    std::array<std::uint32_t, 8> state_{};
    std::array<std::uint8_t, kBlockBytes> buffer_{};
    std::size_t buffered_ = 0;
    std::uint64_t total_bits_ = 0;
};

// Lowercase hex, which is what every signature and body hash in this protocol is written as.
std::string to_hex(const std::uint8_t* bytes, std::size_t len);
std::string to_hex(const Sha256::Digest& d);

}  // namespace dariya
